language: python

python:
  - "3.6"

install:
  - python3 -m venv p2_venv
  - source p2_venv/bin/activate
  - pip3 install --upgrade pip
  - pip install -r requirements.txt

script:
  - python test.py
